[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

# Comment out redirects temporarily for testing
#[[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200
