[build]
  command = "npm install && npm run build"
  publish = "/dist"

# Comment out redirects temporarily for testing
#[[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200
