[build]
  # The build command to run (this runs the build for your React app)
  command = "npm run build"
  
  # The directory to publish the build output (where Vite puts the compiled files)
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

